# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='rec_type',
            field=models.CharField(choices=[('daily_plan', 'Daily Plan'), ('motivation', 'Motivation'), ('weekly_report', 'Weekly Report'), ('monthly_report', 'Monthly Report'), ('tip', 'Tip')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('preference', '⚙️ User Preference'), ('strength', '💪 Observed Strength'), ('weakness', '⚠ Growth Area / Weakness'), ('pattern', '🔄 Recurring Pattern'), ('goal', '🎯 Milestone Goal')], default='preference', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('confidence', models.CharField(default='High', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-updated_at'],
            },
        ),
    ]
