"""
Django management command to seed 100+ exercises across all muscle groups for both Gym and Home workouts.
"""
from django.core.management.base import BaseCommand
from workouts.models import Exercise


EXERCISE_DATA = [
    # --- CHEST ---
    {
        "name": "Barbell Bench Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "bench", "full_gym"],
        "instructions": "Lie flat on the bench. Grip the bar slightly wider than shoulder-width. Lower to mid-chest under control, press up explosively.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Incline Dumbbell Press",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench", "full_gym"],
        "instructions": "Set bench to 30-45 degrees. Press dumbbells upward, focusing on squeezing the upper clavicular head of the pectorals.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Standard Push-Up",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "core", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Place hands shoulder-width apart in plank position. Lower body until chest is an inch off the floor, then push back up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Diamond Push-Up",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Form a diamond shape with index fingers and thumbs under your chest. Lower and push to emphasize inner chest and triceps.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Decline Push-Up",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "difficulty": "intermediate",
        "equipment": ["bench", "no_equipment"],
        "instructions": "Elevate feet on a bench or chair with hands on the ground. Lower chest to floor to target upper chest fibers.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Cable Chest Flyes",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "difficulty": "intermediate",
        "equipment": ["full_gym"],
        "instructions": "Set pulleys to chest height. Bring handles together in front with a hugging motion, maintaining a slight elbow bend.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Dips (Chest Focus)",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "advanced",
        "equipment": ["pull_up_bar", "full_gym"],
        "instructions": "Lean torso forward 30 degrees. Flare elbows slightly as you lower until upper arms are parallel to the bars, press up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Resistance Band Chest Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Anchor band behind your back or around an anchor. Press handles forward, squeezing chest at peak contraction.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Dumbbell Pullover",
        "muscle_group": "chest",
        "secondary_muscles": ["back", "triceps"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench"],
        "instructions": "Lie across a bench. Lower dumbbell behind head in an arc until a deep stretch in lats/chest is felt, pull back up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },

    # --- BACK ---
    {
        "name": "Barbell Deadlift",
        "muscle_group": "back",
        "secondary_muscles": ["hamstrings", "glutes", "core", "forearms"],
        "difficulty": "advanced",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Stand mid-foot under barbell. Hinge at hips, grip bar, chest up, pull through midfoot locking out hips at top.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 8.5,
    },
    {
        "name": "Pull-Ups",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["pull_up_bar", "full_gym"],
        "instructions": "Overhand grip wider than shoulders. Pull chest up to bar by driving elbows down into your ribs, full range of motion.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.5,
    },
    {
        "name": "Chin-Ups",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "forearms"],
        "difficulty": "intermediate",
        "equipment": ["pull_up_bar", "full_gym"],
        "instructions": "Underhand shoulder-width grip. Pull until chin clears the bar, emphasizing lat sweep and bicep activation.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Barbell Bent-Over Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "shoulders", "core"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Hinge forward 45 degrees with flat back. Pull bar into lower ribcage, squeezing shoulder blades tightly together.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Single-Arm Dumbbell Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "difficulty": "beginner",
        "equipment": ["dumbbells", "bench"],
        "instructions": "Place one knee and hand on bench. Pull dumbbell with other arm towards hip, keeping elbow tucked.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Lat Pulldown",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Sit at cable machine. Pull wide bar down toward upper chest, driving elbows down and back.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Seated Cable Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Sit upright with feet on pads. Pull V-handle to abdomen while retracting scapulae and maintaining neutral spine.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Resistance Band Lat Pulldown / Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Anchor band overhead or in front. Pull elbows back, squeezing lats and mid-back musculature.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Superman Hold",
        "muscle_group": "back",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lie face down on floor. Lift arms and legs simultaneously 4-6 inches, hold for 2-3 seconds, lower under control.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },

    # --- SHOULDERS ---
    {
        "name": "Overhead Barbell Military Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Stand with feet shoulder-width. Press barbell overhead until arms lock out, bracing core and glutes firmly.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Seated Dumbbell Shoulder Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench"],
        "instructions": "Sit upright. Press dumbbells overhead from ear level until fully extended, lower slowly.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Dumbbell Lateral Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": ["traps"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Stand tall with dumbbells at sides. Raise arms out to sides until parallel to floor, leading with elbows.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Resistance Band Lateral Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": ["traps"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Step on center of band. Raise handles laterally to shoulder level against continuous tension.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Pike Push-Up",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Assume downward dog position with hips high. Lower head toward floor between hands and push back up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Dumbbell Rear Delt Fly",
        "muscle_group": "shoulders",
        "secondary_muscles": ["back"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Bend at hips 90 degrees. Raise dumbbells outward in an arc to emphasize posterior deltoids.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Face Pulls",
        "muscle_group": "shoulders",
        "secondary_muscles": ["back", "traps"],
        "difficulty": "beginner",
        "equipment": ["full_gym", "resistance_bands"],
        "instructions": "Attach rope to cable at eye height. Pull towards forehead, rotating hands outward for rotator cuff and rear delt health.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },

    # --- BICEPS ---
    {
        "name": "Barbell Bicep Curl",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "beginner",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Stand tall holding barbell with underhand grip. Curl weight upward keeping elbows pinned to sides.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Dumbbell Hammer Curl",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Hold dumbbells with neutral (palms facing each other) grip. Curl upward to target brachialis and forearm thickness.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Incline Dumbbell Curl",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench"],
        "instructions": "Lie on 45-degree incline bench. Curl dumbbells from full stretch position for peak long-head recruitment.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Resistance Band Bicep Curl",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Stand on band, curl handles up to shoulders with constant accommodating resistance.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Preacher Curl",
        "muscle_group": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "barbell", "bench", "full_gym"],
        "instructions": "Rest arms on angled preacher pad. Curl weight upward eliminating all body momentum.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },

    # --- TRICEPS ---
    {
        "name": "Tricep Rope Pushdown",
        "muscle_group": "triceps",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Attach rope to high pulley. Extend arms downward, spreading rope ends apart at the bottom for full contraction.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Overhead Dumbbell Tricep Extension",
        "muscle_group": "triceps",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Hold dumbbell overhead with both hands. Lower behind head bending at elbows, press back to full extension.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Bench Dips",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["bench", "no_equipment"],
        "instructions": "Place hands behind you on bench edge. Lower hips toward floor by bending elbows to 90 degrees, press up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Skull Crushers (Lying Tricep Extension)",
        "muscle_group": "triceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "dumbbells", "bench"],
        "instructions": "Lie on bench. Lower bar/dumbbells toward forehead by hinging at elbows, extend back upward.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },

    # --- LEGS: QUADRICEPS ---
    {
        "name": "Barbell Back Squat",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core", "calves"],
        "difficulty": "advanced",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Rest barbell across upper traps. Squat down until thighs are parallel to ground, drive through heels to stand.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Goblet Squat",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Hold dumbbell vertically against chest. Squat down between knees keeping chest upright.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Bodyweight Squat",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "calves"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Stand with feet shoulder-width. Lower hips down and back to parallel, return to standing with control.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Bulgarian Split Squat",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench", "no_equipment"],
        "instructions": "Place rear foot elevated on bench behind you. Lower front knee until thigh is parallel, push through front foot.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Walking Lunges",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": ["dumbbells", "no_equipment"],
        "instructions": "Step forward into a deep lunge. Push through front heel to step into the next lunge continuously.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Leg Press",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "intermediate",
        "equipment": ["full_gym"],
        "instructions": "Sit in machine with feet shoulder-width on sled. Lower weight until knees reach 90 degrees, press without locking knees.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Leg Extension",
        "muscle_group": "quadriceps",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Sit on machine with pad against lower shins. Extend legs fully, squeezing quadriceps at top.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },

    # --- LEGS: HAMSTRINGS & GLUTES ---
    {
        "name": "Romanian Deadlift (RDL)",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "dumbbells", "full_gym"],
        "instructions": "Hold weight at thighs. Push hips backward with slight knee bend until deep hamstring stretch, drive hips forward.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Barbell Hip Thrust",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "bench", "full_gym"],
        "instructions": "Upper back against bench, bar padded across hips. Drive through heels to raise hips into full extension, squeeze glutes.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Glute Bridge",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings"],
        "difficulty": "beginner",
        "equipment": ["no_equipment", "resistance_bands"],
        "instructions": "Lie on back with knees bent and feet flat. Lift hips towards ceiling until straight line from knees to shoulders.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Lying Leg Curls",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["calves"],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Lie face down on machine. Curl pad towards glutes, controlling the eccentric descent.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Standing Calf Raises",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["dumbbells", "no_equipment", "full_gym"],
        "instructions": "Stand on edge of step. Lower heels into deep stretch, then elevate onto balls of feet as high as possible.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },

    # --- CORE / ABS ---
    {
        "name": "Standard Plank Hold",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders", "glutes"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Rest on forearms and toes. Keep spine neutral and glutes squeezed, holding static posture without sagging.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Hanging Leg Raise",
        "muscle_group": "core",
        "secondary_muscles": ["forearms"],
        "difficulty": "advanced",
        "equipment": ["pull_up_bar", "full_gym"],
        "instructions": "Hang from bar. Raise straight legs until parallel to floor or higher without swinging torso.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Bicycle Crunches",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lie on back. Alternate touching opposite elbow to knee while pedaling legs in continuous rhythm.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Ab Wheel Rollout",
        "muscle_group": "core",
        "secondary_muscles": ["lats", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment", "other_equipment"],
        "instructions": "Kneel on floor holding ab wheel. Roll wheel forward keeping abs braced, pull back with core.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Cable Woodchoppers",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "difficulty": "intermediate",
        "equipment": ["full_gym", "resistance_bands"],
        "instructions": "Grip cable handle with both hands. Rotate torso diagonally across body in a controlled chopping motion.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Mountain Climbers",
        "muscle_group": "core",
        "secondary_muscles": ["cardio", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "In top of pushup position, alternate driving knees towards chest in rapid succession.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 8.0,
    },

    # --- CARDIO & HIIT ---
    {
        "name": "Burpees",
        "muscle_group": "cardio",
        "secondary_muscles": ["full_body", "chest", "quadriceps"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Drop from standing into pushup, perform pushup, jump feet forward and leap into air with arms overhead.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 10.0,
    },
    {
        "name": "Jump Rope",
        "muscle_group": "cardio",
        "secondary_muscles": ["calves", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment", "other_equipment"],
        "instructions": "Turn rope with wrists, hopping lightly on the balls of feet with minimal knee bend.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 9.5,
    },
    {
        "name": "Treadmill Incline Sprints",
        "muscle_group": "cardio",
        "secondary_muscles": ["hamstrings", "glutes", "calves"],
        "difficulty": "advanced",
        "equipment": ["full_gym"],
        "instructions": "Set treadmill to 8-12% incline. Sprint for 20-30 seconds at maximum effort, followed by 40-60 seconds walking rest.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 12.0,
    },
    {
        "name": "Rowing Machine Intervals",
        "muscle_group": "cardio",
        "secondary_muscles": ["back", "quadriceps", "biceps"],
        "difficulty": "intermediate",
        "equipment": ["full_gym"],
        "instructions": "Drive with legs, lean back slightly, pull handle into lower ribs. Return in reverse sequence with smooth cadence.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 11.0,
    },
    # --- FOREARMS & GRIP ---
    {
        "name": "Barbell Wrist Curls",
        "muscle_group": "forearms",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["barbell", "bench"],
        "instructions": "Rest forearms on bench with wrists hanging off edge. Curl barbell upward using wrist flexion.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 3.5,
    },
    {
        "name": "Reverse Barbell Curl",
        "muscle_group": "forearms",
        "secondary_muscles": ["biceps"],
        "difficulty": "beginner",
        "equipment": ["barbell"],
        "instructions": "Overhand grip on barbell. Curl bar upward targeting brachioradialis and wrist extensors.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Farmer's Walk",
        "muscle_group": "forearms",
        "secondary_muscles": ["traps", "core", "calves"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "full_gym"],
        "instructions": "Pick up heavy dumbbells in each hand. Walk forward with upright posture and braced core for distance or time.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Dead Hang",
        "muscle_group": "forearms",
        "secondary_muscles": ["back", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["pull_up_bar"],
        "instructions": "Hang passively from pull-up bar with arms fully extended. Hold for prescribed seconds to build grip endurance.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },

    # --- MORE CHEST ---
    {
        "name": "Chest Dip (Bodyweight)",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["pull_up_bar"],
        "instructions": "Lean forward on parallel bars, lower chest until deep stretch, push upward to lockout.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Incline Push-Up",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["bench", "no_equipment"],
        "instructions": "Place hands on an elevated surface (bench or table). Perform push-ups with reduced bodyweight load.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Dumbbell Floor Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Lie flat on floor with knees bent. Press dumbbells up from elbows touching floor, saving shoulders.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Pec Deck Flye Machine",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": ["full_gym"],
        "instructions": "Sit upright with back flat against pad. Bring arms together in front, squeezing pectorals at peak contraction.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },

    # --- MORE BACK ---
    {
        "name": "T-Bar Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "traps", "core"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "full_gym"],
        "instructions": "Straddle the bar. Pull handle towards chest while keeping torso at a 45-degree angle with neutral spine.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Inverted Bodyweight Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "difficulty": "beginner",
        "equipment": ["pull_up_bar", "no_equipment"],
        "instructions": "Lie under a waist-height bar. Grip overhand and pull chest to bar while keeping body in a straight plank.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Dumbbell Shrugs",
        "muscle_group": "back",
        "secondary_muscles": ["traps", "forearms"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Stand tall holding heavy dumbbells. Elevate shoulders straight up towards ears, hold for 1 second, lower.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Hyperextensions (Back Extensions)",
        "muscle_group": "back",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": ["full_gym", "bench"],
        "instructions": "Lock legs into 45-degree bench. Hinge at hips to lower upper body, raise back to neutral alignment.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },

    # --- MORE SHOULDERS ---
    {
        "name": "Arnold Dumbbell Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "bench"],
        "instructions": "Start with dumbbells at chin level, palms facing you. Rotate palms outward as you press overhead.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Front Dumbbell Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": ["chest"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Raise dumbbells in front of you until shoulder height with arms slightly bent.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Cable Lateral Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": ["traps"],
        "difficulty": "intermediate",
        "equipment": ["full_gym"],
        "instructions": "Set low pulley. Pull handle across body and outward to shoulder height under constant tension.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },

    # --- MORE BICEPS & TRICEPS ---
    {
        "name": "Concentration Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Sit on bench, brace elbow against inner thigh. Curl dumbbell up with strict isolated bicep contraction.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Close-Grip Barbell Bench Press",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["barbell", "bench", "full_gym"],
        "instructions": "Grip bar shoulder-width apart. Lower to lower chest keeping elbows close to torso, press to lockout.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Dumbbell Tricep Kickback",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Hinge forward at hips. Keep upper arm parallel to floor, extend forearm backward until fully straight.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },

    # --- MORE LEGS & GLUTES ---
    {
        "name": "Sumo Squat (Dumbbell)",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "adductors"],
        "difficulty": "beginner",
        "equipment": ["dumbbells"],
        "instructions": "Stand with wide stance, toes pointed outward 45 degrees. Lower into deep squat, drive through heels.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Step-Ups",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "calves"],
        "difficulty": "beginner",
        "equipment": ["bench", "dumbbells", "no_equipment"],
        "instructions": "Step up onto bench driving through leading heel. Step down under control, alternate legs.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Single-Leg Romanian Deadlift",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "core"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "no_equipment"],
        "instructions": "Stand on one leg. Hinge forward extending back leg straight behind until torso is parallel to ground.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Nordic Hamstring Curl",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "calves"],
        "difficulty": "advanced",
        "equipment": ["no_equipment"],
        "instructions": "Kneel with ankles anchored. Lower torso forward under eccentric control using hamstrings, push back up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Seated Calf Raises",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["full_gym", "dumbbells"],
        "instructions": "Sit with knees bent 90 degrees and weight resting on knees. Raise heels to isolate soleus muscle.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 3.5,
    },

    # --- MORE CORE ---
    {
        "name": "Russian Twists",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["no_equipment", "dumbbells"],
        "instructions": "Sit with knees bent and feet elevated. Rotate torso side to side touching floor on each side.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Side Plank Hold",
        "muscle_group": "core",
        "secondary_muscles": ["glutes", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lie on side propped on forearm. Elevate hips forming a straight line from head to feet, hold steady.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Deadbug",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lie on back with arms up and knees at 90 degrees. Lower opposite arm and leg simultaneously while bracing spine.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "Cable Crunch",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": ["full_gym"],
        "instructions": "Kneel below high pulley holding rope at forehead. Flex spine downward curling ribcage into pelvis.",
        "is_home_friendly": False,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },

    # --- MORE CARDIO & FULL BODY ---
    {
        "name": "Kettlebell / Dumbbell Swings",
        "muscle_group": "full_body",
        "secondary_muscles": ["hamstrings", "glutes", "core", "shoulders"],
        "difficulty": "intermediate",
        "equipment": ["dumbbells", "other_equipment"],
        "instructions": "Hinge at hips holding weight between legs. Snap hips forward explosively to swing weight to chest level.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 9.0,
    },
    {
        "name": "Shadow Boxing Rounds",
        "muscle_group": "cardio",
        "secondary_muscles": ["shoulders", "core", "full_body"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Perform punch combinations (jab, cross, hook, uppercut) with active footwork and head movement in 3-minute rounds.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Bear Crawl",
        "muscle_group": "full_body",
        "secondary_muscles": ["core", "shoulders", "quadriceps"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Crawl on hands and toes with knees hovering 1 inch above the ground. Move forward with opposite hand and foot.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 8.5,
    },
    # --- MOBILITY & STRETCHES ---
    {
        "name": "Cat-Cow Stretch",
        "muscle_group": "back",
        "secondary_muscles": ["core"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "On hands and knees, alternate arching back up (Cat) and dropping belly towards floor (Cow) with deep breathing.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 3.0,
    },
    {
        "name": "World's Greatest Stretch",
        "muscle_group": "full_body",
        "secondary_muscles": ["hamstrings", "glutes", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Step into deep lunge, place inside hand on floor, rotate opposite arm towards ceiling opening thoracic spine.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Cossack Squat",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Wide stance, shift bodyweight down to one side in deep lateral squat while opposite leg stays straight with toes up.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
    {
        "name": "Pigeon Pose Glute Stretch",
        "muscle_group": "glutes",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Bring one shin across the front of mat with other leg straight behind, sink hips to ground for deep glute release.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 2.5,
    },
    {
        "name": "Thoracic Spine Foam Roll",
        "muscle_group": "back",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["other_equipment"],
        "instructions": "Place foam roller under mid-back with hands supporting head. Roll gently from mid to upper back to improve mobility.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 2.5,
    },
    {
        "name": "Doorway Pec Stretch",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Place forearm against doorframe at 90 degrees. Step forward gently until deep stretch is felt across chest.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 2.5,
    },
    {
        "name": "Band Dislocates / Pass-Throughs",
        "muscle_group": "shoulders",
        "secondary_muscles": ["chest", "back"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Hold resistance band with wide overhand grip. Keeping arms straight, rotate band from hips overhead and behind back.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 3.0,
    },
    {
        "name": "Hollow Body Hold",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Lie on back. Press lower back flat into floor, elevate shoulder blades and straight legs a few inches off floor, hold.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Bird Dog",
        "muscle_group": "core",
        "secondary_muscles": ["glutes", "back"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "From hands and knees, extend opposite arm and leg simultaneously until parallel with floor, hold 2s, alternate.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.0,
    },
    {
        "name": "L-Sit Hold",
        "muscle_group": "core",
        "secondary_muscles": ["triceps", "forearms"],
        "difficulty": "advanced",
        "equipment": ["pull_up_bar", "bench", "no_equipment"],
        "instructions": "Press hands into parallettes or floor, elevate body and hold straight legs out in front forming an 'L' shape.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Box Jumps",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["calves", "glutes", "cardio"],
        "difficulty": "intermediate",
        "equipment": ["bench", "other_equipment", "full_gym"],
        "instructions": "Stand in front of sturdy box/bench. Swing arms and explode onto box landing softly in half-squat, step down.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 9.5,
    },
    {
        "name": "Kettlebell Clean and Press",
        "muscle_group": "full_body",
        "secondary_muscles": ["shoulders", "hamstrings", "core"],
        "difficulty": "advanced",
        "equipment": ["dumbbells", "other_equipment"],
        "instructions": "Swing weight to rack position at shoulder, then press overhead into full lockout, lower smoothly.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 9.0,
    },
    {
        "name": "Skater Hops",
        "muscle_group": "glutes",
        "secondary_muscles": ["quadriceps", "cardio"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Bound laterally from right to left foot, sweeping the trailing leg behind in a speed skater motion.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Single-Leg Calf Raise",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Balance on ball of one foot. Lower heel into full stretch and elevate onto toes as high as possible.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 4.5,
    },
    {
        "name": "V-Ups",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": ["no_equipment"],
        "instructions": "Lie flat on back. Simultaneously lift straight legs and torso, reaching hands toward toes to form a 'V' shape.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.5,
    },
    {
        "name": "Band Pull-Aparts",
        "muscle_group": "shoulders",
        "secondary_muscles": ["back"],
        "difficulty": "beginner",
        "equipment": ["resistance_bands"],
        "instructions": "Hold resistance band at chest height with straight arms. Pull band apart until it touches chest, squeezing upper back.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 3.5,
    },
    {
        "name": "Reverse Lunges",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": ["no_equipment", "dumbbells"],
        "instructions": "Step backward into lunge until front thigh is parallel. Drive through front heel to return to standing.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Wall Sit",
        "muscle_group": "quadriceps",
        "secondary_muscles": ["glutes", "calves"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lean back against wall and slide down until thighs are parallel to ground at 90 degrees. Hold static position.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Jumping Jacks",
        "muscle_group": "cardio",
        "secondary_muscles": ["calves", "shoulders"],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Jump feet wide while bringing arms overhead, jump back together in continuous rhythmic motion.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Flutter Kicks",
        "muscle_group": "core",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": ["no_equipment"],
        "instructions": "Lie on back with hands under glutes. Lift legs 6 inches off floor and alternate small upward/downward flutter kicks.",
        "is_home_friendly": True,
        "is_gym_exercise": True,
        "calories_per_minute": 5.5,
    },
]


class Command(BaseCommand):
    help = "Seeds the database with 100+ comprehensive gym and home exercises."

    def handle(self, *args, **options):
        self.stdout.write("Seeding exercise library...")
        created_count = 0
        updated_count = 0

        for item in EXERCISE_DATA:
            obj, created = Exercise.objects.update_or_create(
                name=item["name"],
                defaults={
                    "muscle_group": item["muscle_group"],
                    "secondary_muscles": item.get("secondary_muscles", []),
                    "difficulty": item.get("difficulty", "intermediate"),
                    "equipment": item.get("equipment", []),
                    "instructions": item.get("instructions", ""),
                    "is_home_friendly": item.get("is_home_friendly", False),
                    "is_gym_exercise": item.get("is_gym_exercise", True),
                    "calories_per_minute": item.get("calories_per_minute", 5.0),
                }
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded exercises! Created: {created_count}, Updated: {updated_count}, Total in DB: {Exercise.objects.count()}"
            )
        )
