# Generated by Django 5.2.13 on 2026-08-11 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='✅', max_length=10)),
                ('target_type', models.CharField(choices=[('boolean', 'Yes/No'), ('number', 'Number'), ('duration', 'Duration (minutes)')], default='boolean', max_length=20)),
                ('target_value', models.FloatField(default=1, help_text='Target number or 1 for boolean')),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('workout_completed', models.BooleanField(default=False)),
                ('workout_duration_minutes', models.PositiveIntegerField(default=0)),
                ('calories_consumed', models.PositiveIntegerField(default=0)),
                ('protein_consumed', models.FloatField(default=0)),
                ('carbs_consumed', models.FloatField(default=0)),
                ('fat_consumed', models.FloatField(default=0)),
                ('water_liters', models.FloatField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('learning_minutes', models.PositiveIntegerField(default=0)),
                ('reading_done', models.BooleanField(default=False)),
                ('meditation_done', models.BooleanField(default=False)),
                ('daily_score', models.PositiveIntegerField(default=0, help_text='Calculated score out of 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Progress',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
