# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('high', '🔥 High Priority'), ('medium', '⚡ Medium Priority'), ('low', '🌱 Low Priority')], default='medium', max_length=10)),
                ('category', models.CharField(default='General', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyGrowthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('body_score', models.PositiveSmallIntegerField(default=75)),
                ('mind_score', models.PositiveSmallIntegerField(default=75)),
                ('learning_score', models.PositiveSmallIntegerField(default=70)),
                ('career_score', models.PositiveSmallIntegerField(default=65)),
                ('discipline_score', models.PositiveSmallIntegerField(default=75)),
                ('habits_score', models.PositiveSmallIntegerField(default=80)),
                ('overall_score', models.PositiveSmallIntegerField(default=73)),
                ('why_changed_explanation', models.TextField(blank=True, help_text='AI explanation of why scores shifted compared to recent baseline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EveningReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('what_went_well', models.TextField(help_text='What went well today?')),
                ('what_could_be_better', models.TextField(help_text='What could have been better?')),
                ('one_improvement_tomorrow', models.TextField(help_text='What is one thing you will improve tomorrow?')),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
