# Generated by Django 5.2.13 on 2026-08-11 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight_kg', models.FloatField(blank=True, help_text='Current weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('target_weight_kg', models.FloatField(blank=True, help_text='Target weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('fitness_goal', models.CharField(choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('athletic', 'Athletic Body'), ('strength', 'Strength'), ('general', 'General Fitness'), ('maintain', 'Maintain Current Body')], default='general', max_length=20)),
                ('body_goal', models.TextField(blank=True, help_text='Describe your ideal body goal')),
                ('fitness_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('workout_location', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym')], default='home', max_length=10)),
                ('available_equipment', models.JSONField(blank=True, default=list, help_text='List of available equipment')),
                ('daily_workout_minutes', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)])),
                ('workout_days_per_week', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('sleep_target_hours', models.FloatField(default=7.5, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('water_target_liters', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('calorie_target', models.PositiveIntegerField(blank=True, help_text='Daily calorie target (auto-calculated if blank)', null=True)),
                ('protein_target_grams', models.PositiveIntegerField(blank=True, help_text='Daily protein target in grams', null=True)),
                ('self_dev_goals', models.TextField(blank=True, help_text='Comma-separated self-development goals')),
                ('profile_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveIntegerField(default=1)),
                ('avatar_color', models.CharField(default='#6C5CE7', help_text='Hex color for avatar', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
