# Generated by Django 5.2.13 on 2026-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_free_hours',
            field=models.FloatField(default=3.0, help_text='Available hours per day for growth/workout'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_current_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_skills_to_learn',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_target_role',
            field=models.CharField(blank=True, help_text='e.g. Python Backend Developer', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_schedule',
            field=models.CharField(blank=True, help_text='e.g. 9-5 Job, College Student, Freelancer', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_goals_list',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['Python', 'DSA', 'AI/ML', 'English']"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mental_development_goals',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['Better focus', 'Reduce procrastination', 'Better sleep']"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_long_term_goals',
            field=models.TextField(blank=True, help_text='Custom 5-10 year aspirations'),
        ),
    ]
