# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTradeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_offering', models.CharField(help_text='e.g. Python & Django, LeetCode DSA, Spoken English', max_length=150)),
                ('offering_proficiency', models.CharField(choices=[('intermediate', 'Intermediate Practitioner'), ('advanced', 'Advanced / Professional'), ('native_fluent', 'Native / Fluent (Language)')], default='intermediate', max_length=30)),
                ('skill_seeking', models.CharField(help_text='e.g. Machine Learning, System Design, German', max_length=150)),
                ('description', models.TextField(help_text="Describe how you'd like to collaborate (e.g. 1-hour weekly Zoom sessions).")),
                ('preferred_schedule', models.CharField(default='Weekends / Evenings', max_length=150)),
                ('contact_handle', models.CharField(blank=True, help_text='Email, Discord, or Telegram handle', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_message', models.TextField(help_text='Introduce yourself and explain what you can share.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted & Connected'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='skills_trade.skilltradelisting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
