# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_year_vision', models.CharField(help_text='e.g. Become a Lead AI Architect & Achieve Complete Financial Independence', max_length=250)),
                ('yearly_goal', models.CharField(help_text='e.g. Land Senior Backend/AI Role & Save $20k', max_length=250)),
                ('monthly_goal', models.CharField(help_text='e.g. Build 2 Production AI Projects & Solve 60 LeetCode Mediums', max_length=250)),
                ('weekly_goal', models.CharField(help_text='e.g. Complete System Design Module & 5 Gym Sessions', max_length=250)),
                ('daily_action', models.CharField(help_text='e.g. 90 min focused coding + 45 min workout today', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_hierarchies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
