# Generated by Django 5.2.13 on 2026-08-11 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list, help_text='Required equipment list')),
                ('instructions', models.TextField(blank=True)),
                ('is_home_friendly', models.BooleanField(default=False)),
                ('is_gym_exercise', models.BooleanField(default=True)),
                ('calories_per_minute', models.FloatField(default=5.0)),
                ('alternative_exercises', models.ManyToManyField(blank=True, to='workouts.exercise')),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('target_muscle_groups', models.JSONField(blank=True, default=list)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=45)),
                ('difficulty_level', models.CharField(default='intermediate', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('user_rating', models.PositiveIntegerField(blank=True, help_text='1-5 difficulty rating from user', null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10', help_text='e.g. 10, 8-12, AMRAP', max_length=20)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('actual_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_reps', models.CharField(blank=True, max_length=50)),
                ('actual_weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
