# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Python Backend, DSA in C++, Deep Learning', max_length=150)),
                ('category', models.CharField(choices=[('programming', 'Programming & Software'), ('dsa', 'Data Structures & Algorithms'), ('ai_ml', 'AI & Machine Learning'), ('math', 'Mathematics & Logic'), ('communication', 'Communication & English'), ('other', 'Other Skills')], default='programming', max_length=30)),
                ('target_hours', models.PositiveIntegerField(default=50)),
                ('completed_hours', models.FloatField(default=0.0)),
                ('roadmap', models.JSONField(blank=True, default=list)),
                ('current_topic', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('topics_covered', models.CharField(max_length=250)),
                ('key_takeaways', models.TextField(blank=True)),
                ('practice_problems_solved', models.PositiveIntegerField(default=0)),
                ('revision_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.learninggoal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
