# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('project', 'Portfolio Project'), ('interview_prep', 'Interview Practice'), ('resume', 'Resume / Portfolio'), ('job_application', 'Job Application'), ('certification', 'Certification / Exam')], default='project', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(default='Software Engineer', help_text='e.g. Python Backend Developer, AI Engineer, Data Scientist', max_length=150)),
                ('target_industry', models.CharField(blank=True, max_length=150)),
                ('target_timeline', models.CharField(default='6 months', max_length=100)),
                ('current_status', models.CharField(default='Preparing for interviews', max_length=100)),
                ('resume_notes', models.TextField(blank=True)),
                ('interview_readiness_score', models.PositiveIntegerField(default=50, help_text='0 to 100%')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('learning', 'Learning / Needs Work ⚠'), ('competent', 'Competent / Proficient ✓'), ('advanced', 'Advanced / Expert 🌟')], default='learning', max_length=20)),
                ('is_critical_gap', models.BooleanField(default=False)),
                ('priority_order', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority_order', 'skill_name'],
            },
        ),
    ]
