# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('coach', '🤖 AI Coach Notice'), ('workout', '💪 Workout Reminder'), ('habit', '🎯 Habit Check'), ('trade', '🤝 Skill Trade Update'), ('system', '⚡ System Alert')], default='coach', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_reminder', models.BooleanField(default=True, help_text='Daily workout prompt')),
                ('water_reminder', models.BooleanField(default=True, help_text='Hydration check')),
                ('meal_reminder', models.BooleanField(default=True, help_text='Food logging reminders')),
                ('learning_reminder', models.BooleanField(default=True, help_text='Study & skill session prompt')),
                ('habit_reminder', models.BooleanField(default=True, help_text='Daily habit check')),
                ('sleep_reminder', models.BooleanField(default=True, help_text='Bedtime wind-down reminder')),
                ('reflection_reminder', models.BooleanField(default=True, help_text='Evening review prompt')),
                ('morning_reminder_time', models.TimeField(default='08:00:00')),
                ('evening_reminder_time', models.TimeField(default='21:30:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
