# Generated by Django 5.2.13 on 2026-08-11 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Write your thoughts, challenges, and reflections here.')),
                ('ai_reflection', models.TextField(blank=True)),
                ('detected_patterns', models.JSONField(blank=True, default=list, help_text='Identified habits, procrastination cues, or strengths')),
                ('actionable_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mood', models.PositiveSmallIntegerField(default=7, help_text='1 (Low) to 10 (Excellent)')),
                ('energy', models.PositiveSmallIntegerField(default=7, help_text='1 (Exhausted) to 10 (High Energy)')),
                ('focus', models.PositiveSmallIntegerField(default=7, help_text='1 (Distracted) to 10 (Laser Focused)')),
                ('stress', models.PositiveSmallIntegerField(default=4, help_text='1 (Calm) to 10 (High Stress)')),
                ('motivation', models.PositiveSmallIntegerField(default=7, help_text='1 (Zero) to 10 (Unstoppable)')),
                ('sleep_quality', models.PositiveSmallIntegerField(default=7, help_text='1 (Poor) to 10 (Restful)')),
                ('mental_clarity', models.PositiveSmallIntegerField(default=7, help_text='1 (Brain Fog) to 10 (Clear)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
